# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agentic_search_done_event import AgenticSearchDoneEvent
    from .agentic_search_done_event_diagnostics import AgenticSearchDoneEventDiagnostics
    from .agentic_search_error_event import AgenticSearchErrorEvent
    from .agentic_search_event import (
        AgenticSearchEvent,
        AgenticSearchEvent_Done,
        AgenticSearchEvent_Error,
        AgenticSearchEvent_Reranking,
        AgenticSearchEvent_Started,
        AgenticSearchEvent_Thinking,
        AgenticSearchEvent_ToolCall,
    )
    from .agentic_search_request import AgenticSearchRequest
    from .agentic_search_reranking_event import AgenticSearchRerankingEvent
    from .agentic_search_reranking_event_diagnostics import AgenticSearchRerankingEventDiagnostics
    from .agentic_search_started_event import AgenticSearchStartedEvent
    from .agentic_search_thinking_event import AgenticSearchThinkingEvent
    from .agentic_search_thinking_event_diagnostics import AgenticSearchThinkingEventDiagnostics
    from .agentic_search_tool_call_event import AgenticSearchToolCallEvent
    from .agentic_search_tool_call_event_diagnostics import AgenticSearchToolCallEventDiagnostics
    from .agentic_search_tool_call_event_diagnostics_stats import AgenticSearchToolCallEventDiagnosticsStats
    from .agentic_search_tool_call_event_tool_name import AgenticSearchToolCallEventToolName
    from .auth_provider_authentication import AuthProviderAuthentication
    from .authentication_details import AuthenticationDetails
    from .authentication_method import AuthenticationMethod
    from .behavior_config import BehaviorConfig
    from .collect_tool_stats import CollectToolStats
    from .collection import Collection
    from .collection_status import CollectionStatus
    from .config_field import ConfigField
    from .conflict_error_response import ConflictErrorResponse
    from .count_tool_stats import CountToolStats
    from .cursor_config import CursorConfig
    from .delivery_attempt import DeliveryAttempt
    from .destination_config import DestinationConfig
    from .direct_authentication import DirectAuthentication
    from .entity_summary import EntitySummary
    from .entity_type_stats import EntityTypeStats
    from .error_tool_stats import ErrorToolStats
    from .event_type import EventType
    from .fields import Fields
    from .filter_condition import FilterCondition
    from .filter_group import FilterGroup
    from .filter_operator import FilterOperator
    from .filterable_field import FilterableField
    from .finish_tool_stats import FinishToolStats
    from .handler_config import HandlerConfig
    from .health_status import HealthStatus
    from .http_validation_error import HttpValidationError
    from .navigate_tool_stats import NavigateToolStats
    from .not_found_error_response import NotFoundErrorResponse
    from .o_auth_browser_authentication import OAuthBrowserAuthentication
    from .o_auth_token_authentication import OAuthTokenAuthentication
    from .rate_limit_error_response import RateLimitErrorResponse
    from .read_tool_stats import ReadToolStats
    from .recovery_task import RecoveryTask
    from .retrieval_strategy import RetrievalStrategy
    from .review_tool_stats import ReviewToolStats
    from .schedule_config import ScheduleConfig
    from .schedule_details import ScheduleDetails
    from .search_access_control import SearchAccessControl
    from .search_breadcrumb import SearchBreadcrumb
    from .search_result import SearchResult
    from .search_system_metadata import SearchSystemMetadata
    from .search_tool_stats import SearchToolStats
    from .search_v_2_response import SearchV2Response
    from .source import Source
    from .source_connection import SourceConnection
    from .source_connection_job import SourceConnectionJob
    from .source_connection_list_item import SourceConnectionListItem
    from .source_connection_status import SourceConnectionStatus
    from .source_connection_summary import SourceConnectionSummary
    from .sync_config import SyncConfig
    from .sync_details import SyncDetails
    from .sync_job_details import SyncJobDetails
    from .sync_job_status import SyncJobStatus
    from .validation_error import ValidationError
    from .validation_error_detail import ValidationErrorDetail
    from .validation_error_loc_item import ValidationErrorLocItem
    from .validation_error_response import ValidationErrorResponse
    from .value import Value
    from .webhook_message import WebhookMessage
    from .webhook_message_with_attempts import WebhookMessageWithAttempts
    from .webhook_subscription import WebhookSubscription
    from .webhook_subscription_detail import WebhookSubscriptionDetail
_dynamic_imports: typing.Dict[str, str] = {
    "AgenticSearchDoneEvent": ".agentic_search_done_event",
    "AgenticSearchDoneEventDiagnostics": ".agentic_search_done_event_diagnostics",
    "AgenticSearchErrorEvent": ".agentic_search_error_event",
    "AgenticSearchEvent": ".agentic_search_event",
    "AgenticSearchEvent_Done": ".agentic_search_event",
    "AgenticSearchEvent_Error": ".agentic_search_event",
    "AgenticSearchEvent_Reranking": ".agentic_search_event",
    "AgenticSearchEvent_Started": ".agentic_search_event",
    "AgenticSearchEvent_Thinking": ".agentic_search_event",
    "AgenticSearchEvent_ToolCall": ".agentic_search_event",
    "AgenticSearchRequest": ".agentic_search_request",
    "AgenticSearchRerankingEvent": ".agentic_search_reranking_event",
    "AgenticSearchRerankingEventDiagnostics": ".agentic_search_reranking_event_diagnostics",
    "AgenticSearchStartedEvent": ".agentic_search_started_event",
    "AgenticSearchThinkingEvent": ".agentic_search_thinking_event",
    "AgenticSearchThinkingEventDiagnostics": ".agentic_search_thinking_event_diagnostics",
    "AgenticSearchToolCallEvent": ".agentic_search_tool_call_event",
    "AgenticSearchToolCallEventDiagnostics": ".agentic_search_tool_call_event_diagnostics",
    "AgenticSearchToolCallEventDiagnosticsStats": ".agentic_search_tool_call_event_diagnostics_stats",
    "AgenticSearchToolCallEventToolName": ".agentic_search_tool_call_event_tool_name",
    "AuthProviderAuthentication": ".auth_provider_authentication",
    "AuthenticationDetails": ".authentication_details",
    "AuthenticationMethod": ".authentication_method",
    "BehaviorConfig": ".behavior_config",
    "CollectToolStats": ".collect_tool_stats",
    "Collection": ".collection",
    "CollectionStatus": ".collection_status",
    "ConfigField": ".config_field",
    "ConflictErrorResponse": ".conflict_error_response",
    "CountToolStats": ".count_tool_stats",
    "CursorConfig": ".cursor_config",
    "DeliveryAttempt": ".delivery_attempt",
    "DestinationConfig": ".destination_config",
    "DirectAuthentication": ".direct_authentication",
    "EntitySummary": ".entity_summary",
    "EntityTypeStats": ".entity_type_stats",
    "ErrorToolStats": ".error_tool_stats",
    "EventType": ".event_type",
    "Fields": ".fields",
    "FilterCondition": ".filter_condition",
    "FilterGroup": ".filter_group",
    "FilterOperator": ".filter_operator",
    "FilterableField": ".filterable_field",
    "FinishToolStats": ".finish_tool_stats",
    "HandlerConfig": ".handler_config",
    "HealthStatus": ".health_status",
    "HttpValidationError": ".http_validation_error",
    "NavigateToolStats": ".navigate_tool_stats",
    "NotFoundErrorResponse": ".not_found_error_response",
    "OAuthBrowserAuthentication": ".o_auth_browser_authentication",
    "OAuthTokenAuthentication": ".o_auth_token_authentication",
    "RateLimitErrorResponse": ".rate_limit_error_response",
    "ReadToolStats": ".read_tool_stats",
    "RecoveryTask": ".recovery_task",
    "RetrievalStrategy": ".retrieval_strategy",
    "ReviewToolStats": ".review_tool_stats",
    "ScheduleConfig": ".schedule_config",
    "ScheduleDetails": ".schedule_details",
    "SearchAccessControl": ".search_access_control",
    "SearchBreadcrumb": ".search_breadcrumb",
    "SearchResult": ".search_result",
    "SearchSystemMetadata": ".search_system_metadata",
    "SearchToolStats": ".search_tool_stats",
    "SearchV2Response": ".search_v_2_response",
    "Source": ".source",
    "SourceConnection": ".source_connection",
    "SourceConnectionJob": ".source_connection_job",
    "SourceConnectionListItem": ".source_connection_list_item",
    "SourceConnectionStatus": ".source_connection_status",
    "SourceConnectionSummary": ".source_connection_summary",
    "SyncConfig": ".sync_config",
    "SyncDetails": ".sync_details",
    "SyncJobDetails": ".sync_job_details",
    "SyncJobStatus": ".sync_job_status",
    "ValidationError": ".validation_error",
    "ValidationErrorDetail": ".validation_error_detail",
    "ValidationErrorLocItem": ".validation_error_loc_item",
    "ValidationErrorResponse": ".validation_error_response",
    "Value": ".value",
    "WebhookMessage": ".webhook_message",
    "WebhookMessageWithAttempts": ".webhook_message_with_attempts",
    "WebhookSubscription": ".webhook_subscription",
    "WebhookSubscriptionDetail": ".webhook_subscription_detail",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AgenticSearchDoneEvent",
    "AgenticSearchDoneEventDiagnostics",
    "AgenticSearchErrorEvent",
    "AgenticSearchEvent",
    "AgenticSearchEvent_Done",
    "AgenticSearchEvent_Error",
    "AgenticSearchEvent_Reranking",
    "AgenticSearchEvent_Started",
    "AgenticSearchEvent_Thinking",
    "AgenticSearchEvent_ToolCall",
    "AgenticSearchRequest",
    "AgenticSearchRerankingEvent",
    "AgenticSearchRerankingEventDiagnostics",
    "AgenticSearchStartedEvent",
    "AgenticSearchThinkingEvent",
    "AgenticSearchThinkingEventDiagnostics",
    "AgenticSearchToolCallEvent",
    "AgenticSearchToolCallEventDiagnostics",
    "AgenticSearchToolCallEventDiagnosticsStats",
    "AgenticSearchToolCallEventToolName",
    "AuthProviderAuthentication",
    "AuthenticationDetails",
    "AuthenticationMethod",
    "BehaviorConfig",
    "CollectToolStats",
    "Collection",
    "CollectionStatus",
    "ConfigField",
    "ConflictErrorResponse",
    "CountToolStats",
    "CursorConfig",
    "DeliveryAttempt",
    "DestinationConfig",
    "DirectAuthentication",
    "EntitySummary",
    "EntityTypeStats",
    "ErrorToolStats",
    "EventType",
    "Fields",
    "FilterCondition",
    "FilterGroup",
    "FilterOperator",
    "FilterableField",
    "FinishToolStats",
    "HandlerConfig",
    "HealthStatus",
    "HttpValidationError",
    "NavigateToolStats",
    "NotFoundErrorResponse",
    "OAuthBrowserAuthentication",
    "OAuthTokenAuthentication",
    "RateLimitErrorResponse",
    "ReadToolStats",
    "RecoveryTask",
    "RetrievalStrategy",
    "ReviewToolStats",
    "ScheduleConfig",
    "ScheduleDetails",
    "SearchAccessControl",
    "SearchBreadcrumb",
    "SearchResult",
    "SearchSystemMetadata",
    "SearchToolStats",
    "SearchV2Response",
    "Source",
    "SourceConnection",
    "SourceConnectionJob",
    "SourceConnectionListItem",
    "SourceConnectionStatus",
    "SourceConnectionSummary",
    "SyncConfig",
    "SyncDetails",
    "SyncJobDetails",
    "SyncJobStatus",
    "ValidationError",
    "ValidationErrorDetail",
    "ValidationErrorLocItem",
    "ValidationErrorResponse",
    "Value",
    "WebhookMessage",
    "WebhookMessageWithAttempts",
    "WebhookSubscription",
    "WebhookSubscriptionDetail",
]
