# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgenticSearchAccessControl(UniversalBaseModel):
    """
    Access control in agentic search result.
    """

    viewers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Principal IDs who can view this entity. None if unknown.
    """

    is_public: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this entity is publicly accessible. None if unknown.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
