# This file was auto-generated by Fern from our API Definition.

import typing

AgenticSearchFilterableField = typing.Union[
    typing.Literal[
        "entity_id",
        "name",
        "created_at",
        "updated_at",
        "breadcrumbs.entity_id",
        "breadcrumbs.name",
        "breadcrumbs.entity_type",
        "airweave_system_metadata.entity_type",
        "airweave_system_metadata.source_name",
        "airweave_system_metadata.original_entity_id",
        "airweave_system_metadata.chunk_index",
        "airweave_system_metadata.sync_id",
        "airweave_system_metadata.sync_job_id",
    ],
    typing.Any,
]
