# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgenticSearchDoneEventDiagnostics(UniversalBaseModel):
    total_iterations: typing.Optional[int] = None
    all_seen_entity_ids: typing.Optional[typing.List[str]] = None
    all_read_entity_ids: typing.Optional[typing.List[str]] = None
    all_collected_entity_ids: typing.Optional[typing.List[str]] = None
    max_iterations_hit: typing.Optional[bool] = None
    total_llm_retries: typing.Optional[int] = None
    stagnation_nudges_sent: typing.Optional[int] = None
    prompt_tokens: typing.Optional[int] = None
    completion_tokens: typing.Optional[int] = None
    cache_creation_input_tokens: typing.Optional[int] = None
    cache_read_input_tokens: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
