# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AgenticSearchBreadcrumb(UniversalBaseModel):
    """
    Breadcrumb in agentic search result.
    """

    entity_id: str = pydantic.Field()
    """
    ID of the entity in the source.
    """

    name: str = pydantic.Field()
    """
    Display name of the entity.
    """

    entity_type: str = pydantic.Field()
    """
    Entity class name (e.g., 'AsanaProjectEntity').
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
