# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agentic_search_tool_call_event_diagnostics_stats import AgenticSearchToolCallEventDiagnosticsStats


class AgenticSearchToolCallEventDiagnostics(UniversalBaseModel):
    iteration: typing.Optional[int] = None
    tool_call_id: typing.Optional[str] = None
    arguments: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Full LLM-generated tool input.
    """

    stats: typing.Optional[AgenticSearchToolCallEventDiagnosticsStats] = pydantic.Field(default=None)
    """
    Output stats. Shape depends on tool_name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
