# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agentic_search_done_event_diagnostics import AgenticSearchDoneEventDiagnostics
from .search_result import SearchResult


class AgenticSearchDoneEvent(UniversalBaseModel):
    results: typing.List[SearchResult] = pydantic.Field()
    """
    Full result set.
    """

    duration_ms: int
    diagnostics: typing.Optional[AgenticSearchDoneEventDiagnostics] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
