# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agentic_search_filter_condition import AgenticSearchFilterCondition


class AgenticSearchFilterGroup(UniversalBaseModel):
    """
    A group of filter conditions combined with AND.

    Multiple filter groups are combined with OR, allowing expressions like:
    (A AND B) OR (C AND D)

    Examples:
        Single group (AND):
            {"conditions": [
                {"field": "airweave_system_metadata.source_name",
                 "operator": "equals", "value": "slack"},
                {"field": "airweave_system_metadata.entity_type",
                 "operator": "equals", "value": "SlackMessageEntity"}
            ]}

        Multiple groups (OR between groups, AND within):
            [
                {"conditions": [{"field": "name", "operator": "equals",
                                 "value": "doc1"}]},
                {"conditions": [{"field": "name", "operator": "equals",
                                 "value": "doc2"}]}
            ]

        Breadcrumb filtering:
            {"conditions": [
                {"field": "breadcrumbs.name", "operator": "contains",
                 "value": "Engineering"}
            ]}
    """

    conditions: typing.List[AgenticSearchFilterCondition] = pydantic.Field()
    """
    Filter conditions within this group, combined with AND
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
