# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import datetime as dt
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ApiKeyCreate(UniversalBaseModel):
    """
    Schema for creating an APIKey object.
    """

    expiration_date: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Expiration date for the API key, defaults to 180 days from now
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
