# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuthProviderAuth(UniversalBaseModel):
    """
    Authentication via external provider.
    """

    provider_name: str = pydantic.Field()
    """
    Auth provider name
    """

    provider_account_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Provider account ID
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
