# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .schedule_config import ScheduleConfig


class AuthProviderCreate(UniversalBaseModel):
    """
    Create source connection using external auth provider.
    """

    name: str
    short_name: str = pydantic.Field()
    """
    Source short_name identifier (e.g., 'slack', 'github')
    """

    readable_collection_id: str = pydantic.Field()
    """
    Collection readable ID
    """

    description: typing.Optional[str] = None
    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Source-specific configuration
    """

    schedule: typing.Optional[ScheduleConfig] = None
    sync_immediately: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Run initial sync after creation
    """

    provider_id: str = pydantic.Field()
    """
    Auth provider connection ID
    """

    provider_config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Provider-specific config
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
