# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ConflictErrorResponse(UniversalBaseModel):
    """
    Response returned when a resource conflict occurs (HTTP 409).

    This typically occurs when attempting to create a resource that already exists,
    or when an operation cannot be completed due to the current state of a resource.
    """

    detail: str = pydantic.Field()
    """
    Error message describing the conflict
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
