# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeliveryAttempt(UniversalBaseModel):
    """
    A delivery attempt for a webhook message.

    Each time Airweave attempts to deliver a message to your webhook endpoint,
    a delivery attempt is recorded. Failed attempts are automatically retried
    with exponential backoff.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for this delivery attempt
    """

    message_id: str = pydantic.Field()
    """
    The event message that was being delivered
    """

    endpoint_id: str = pydantic.Field()
    """
    The subscription endpoint this was delivered to
    """

    response: typing.Optional[str] = pydantic.Field(default=None)
    """
    The response body returned by your webhook endpoint (truncated to 1KB)
    """

    response_status_code: int = pydantic.Field()
    """
    HTTP status code returned by your webhook endpoint. 2xx codes indicate success; other codes trigger retries.
    """

    status: str = pydantic.Field()
    """
    Delivery status: `success` (2xx response), `pending` (awaiting delivery), or `failed` (non-2xx response or timeout)
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    When this delivery attempt occurred (ISO 8601 format, UTC)
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL that was called
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
