# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EntityCountWithDefinition(UniversalBaseModel):
    """
    Entity count with entity definition details.

    After the entity_definition table elimination, name/type/description
    are populated from the in-memory registry or derived from the short_name.
    """

    count: int
    entity_definition_short_name: str
    entity_definition_name: str
    entity_definition_type: str
    entity_definition_description: typing.Optional[str] = None
    modified_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
