# This file was auto-generated by Fern from our API Definition.

import typing

EventType = typing.Union[
    typing.Literal[
        "sync.pending",
        "sync.running",
        "sync.completed",
        "sync.failed",
        "sync.cancelled",
        "source_connection.created",
        "source_connection.auth_completed",
        "source_connection.deleted",
        "collection.created",
        "collection.updated",
        "collection.deleted",
    ],
    typing.Any,
]
