# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .filter_group import FilterGroup
from .retrieval_strategy import RetrievalStrategy


class InstantSearchRequest(UniversalBaseModel):
    """
    Instant search request — embed query, fire at Vespa, return results.
    """

    query: str = pydantic.Field()
    """
    Search query text.
    """

    retrieval_strategy: typing.Optional[RetrievalStrategy] = pydantic.Field(default=None)
    """
    Which retrieval strategy to use.
    """

    filter: typing.Optional[typing.List[FilterGroup]] = pydantic.Field(default=None)
    """
    Filter groups (combined with OR).
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Max results to return.
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of results to skip.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
