# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_summary import EntitySummary


class NavigateToolStats(UniversalBaseModel):
    """
    Stats from get_children, get_siblings, or get_parent.
    """

    result_count: typing.Optional[int] = None
    context_label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable label, e.g. 'children of chan-engineering'.
    """

    first_results: typing.Optional[typing.List[EntitySummary]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
