# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .schedule_config import ScheduleConfig


class OAuthByocCreate(UniversalBaseModel):
    """
    Create source connection with bring-your-own-client OAuth.
    """

    name: str
    short_name: str = pydantic.Field()
    """
    Source short_name identifier (e.g., 'slack', 'github')
    """

    readable_collection_id: str = pydantic.Field()
    """
    Collection readable ID
    """

    description: typing.Optional[str] = None
    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Source-specific configuration
    """

    schedule: typing.Optional[ScheduleConfig] = None
    sync_immediately: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Run initial sync after creation
    """

    client_id: str = pydantic.Field()
    """
    OAuth client ID
    """

    client_secret: str = pydantic.Field()
    """
    OAuth client secret
    """

    redirect_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    OAuth callback redirect URL
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
