# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RateLimitErrorResponse(UniversalBaseModel):
    """
    Response returned when rate limit is exceeded (HTTP 429).

    The API enforces rate limits to ensure fair usage. When exceeded,
    wait for the duration specified in the Retry-After header before retrying.
    """

    detail: str = pydantic.Field()
    """
    Error message explaining the rate limit
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
