# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SearchResponse(UniversalBaseModel):
    """
    Search response containing results and optional AI-generated completion.

    Each result includes the matched entity's content, metadata, relevance score,
    and source information.
    """

    results: typing.List[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field()
    """
    Array of search result objects containing the found documents, records, or data entities. Each result includes entity_id, source_name, md_content, metadata, score, breadcrumbs, and url.
    """

    completion: typing.Optional[str] = pydantic.Field(default=None)
    """
    AI-generated natural language answer to your query based on the search results. Only included when generate_answer is true in the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
