# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .search_result import SearchResult


class SearchV2Response(UniversalBaseModel):
    """
    Unified response for all search tiers.
    """

    results: typing.Optional[typing.List[SearchResult]] = pydantic.Field(default=None)
    """
    Search results ordered by relevance.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
