# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_summary import EntitySummary


class SearchToolStats(UniversalBaseModel):
    """
    Stats from a search tool call.
    """

    result_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total results returned.
    """

    new_results: typing.Optional[int] = pydantic.Field(default=None)
    """
    Results not seen in previous searches.
    """

    first_results: typing.Optional[typing.List[EntitySummary]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
