# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SourceConnectionValidate(UniversalBaseModel):
    """
    Schema for validating source connection credentials.
    """

    short_name: str = pydantic.Field()
    """
    Source short_name identifier
    """

    config: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Source-specific configuration
    """

    credentials: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None
    access_token: typing.Optional[str] = None
    refresh_token: typing.Optional[str] = None
    token_expires_at: typing.Optional[dt.datetime] = None
    client_id: typing.Optional[str] = None
    client_secret: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
