# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .authentication_method import AuthenticationMethod
from .source_connection_status import SourceConnectionStatus


class SourceConnectionListItem(UniversalBaseModel):
    """
    Lightweight source connection representation for list views.

    Contains essential fields for display and navigation. For full details
    including sync history and configuration, use the GET /{id} endpoint.
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the source connection
    """

    name: str = pydantic.Field()
    """
    Display name of the connection
    """

    short_name: str = pydantic.Field()
    """
    Source type identifier
    """

    readable_collection_id: str = pydantic.Field()
    """
    Collection this connection belongs to
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When the connection was created (ISO 8601)
    """

    modified_at: dt.datetime = pydantic.Field()
    """
    When the connection was last modified (ISO 8601)
    """

    is_authenticated: bool = pydantic.Field()
    """
    Whether the connection has valid credentials
    """

    entity_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    Total number of entities synced from this connection
    """

    federated_search: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this source uses federated (real-time) search instead of syncing
    """

    auth_method: AuthenticationMethod = pydantic.Field()
    """
    Get authentication method from database value.
    """

    status: SourceConnectionStatus = pydantic.Field()
    """
    Compute connection status from current state.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
