# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .delivery_attempt import DeliveryAttempt


class WebhookSubscription(UniversalBaseModel):
    """
    A webhook subscription (endpoint) configuration.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for this subscription (UUID format)
    """

    url: str = pydantic.Field()
    """
    The URL where webhook events are delivered
    """

    filter_types: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Event types this subscription is filtered to receive. Available types: `sync.pending`, `sync.running`, `sync.completed`, `sync.failed`, `sync.cancelled`.
    """

    disabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this subscription is currently disabled. Disabled subscriptions do not receive event deliveries.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional human-readable description of this subscription
    """

    created_at: dt.datetime = pydantic.Field()
    """
    When this subscription was created (ISO 8601 format, UTC)
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    When this subscription was last updated (ISO 8601 format, UTC)
    """

    delivery_attempts: typing.Optional[typing.List[DeliveryAttempt]] = pydantic.Field(default=None)
    """
    Recent delivery attempts for this subscription. Only included when fetching a single subscription via GET /subscriptions/{id}.
    """

    secret: typing.Optional[str] = pydantic.Field(default=None)
    """
    The signing secret for webhook signature verification. Only included when include_secret=true is passed to the API. Keep this secret secure.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
