# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.event_type import EventType
from ..types.recovery_task import RecoveryTask
from ..types.webhook_message import WebhookMessage
from ..types.webhook_message_with_attempts import WebhookMessageWithAttempts
from ..types.webhook_subscription import WebhookSubscription
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def get_messages(
        self,
        *,
        event_types: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[WebhookMessage]:
        """
        Retrieve all webhook messages for your organization.

        Webhook messages represent payloads that were sent (or attempted to be sent)
        to your subscribed endpoints. Each message contains the event type, payload data,
        and delivery status information.

        Use the `event_types` query parameter to filter messages by specific event types,
        such as `sync.completed` or `sync.failed`.

        Parameters
        ----------
        event_types : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter messages by event type(s). Accepts multiple values, e.g., `?event_types=sync.completed&event_types=sync.failed`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WebhookMessage]
            List of webhook messages

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_messages()
        """
        _response = self._raw_client.get_messages(event_types=event_types, request_options=request_options)
        return _response.data

    def get_message(
        self,
        message_id: str,
        *,
        include_attempts: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookMessageWithAttempts:
        """
        Retrieve a specific webhook message by its ID.

        Returns the full message details including the event type, payload data,
        timestamp, and delivery channel information. Use this to inspect the
        exact payload that was sent to your webhook endpoints.

        Use `include_attempts=true` to also retrieve delivery attempts for this message,
        which include HTTP response codes, response bodies, and timestamps for debugging
        delivery failures.

        Parameters
        ----------
        message_id : str
            The unique identifier of the message to retrieve (UUID).

        include_attempts : typing.Optional[bool]
            Include delivery attempts for this message. Each attempt includes the HTTP response code, response body, and timestamp.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookMessageWithAttempts
            Webhook message details

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_message(
            message_id="550e8400-e29b-41d4-a716-446655440000",
            include_attempts=True,
        )
        """
        _response = self._raw_client.get_message(
            message_id, include_attempts=include_attempts, request_options=request_options
        )
        return _response.data

    def get_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[WebhookSubscription]:
        """
        List all webhook subscriptions for your organization.

        Returns all configured webhook endpoints, including their URLs, subscribed
        event types, and current status (enabled/disabled). Use this to audit
        your webhook configuration or find a specific subscription.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WebhookSubscription]
            List of webhook subscriptions

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_subscriptions()
        """
        _response = self._raw_client.get_subscriptions(request_options=request_options)
        return _response.data

    def create_subscription(
        self,
        *,
        url: str,
        event_types: typing.Sequence[EventType],
        secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Create a new webhook subscription.

        Webhook subscriptions allow you to receive real-time notifications when events
        occur in Airweave. When you create a subscription, you specify:

        - **URL**: The HTTPS endpoint where events will be delivered
        - **Event Types**: Which events you want to receive (e.g., `sync.completed`, `sync.failed`)
        - **Secret** (optional): A custom signing secret for verifying webhook signatures

        After creation, Airweave will send HTTP POST requests to your URL whenever
        matching events occur. Each request includes a signature header for verification.

        Parameters
        ----------
        url : str
            The HTTPS URL where webhook events will be delivered. Must be a publicly accessible endpoint that returns a 2xx status code.

        event_types : typing.Sequence[EventType]
            List of event types to subscribe to. Events not in this list will not be delivered to this subscription. Available types: `sync.pending`, `sync.running`, `sync.completed`, `sync.failed`, `sync.cancelled`.

        secret : typing.Optional[str]
            Optional custom signing secret for webhook signature verification. If not provided, a secure secret will be auto-generated. Must be at least 24 characters if specified.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Created subscription

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.create_subscription(
            url="https://api.mycompany.com/webhooks/airweave",
            event_types=["sync.completed", "sync.failed"],
        )
        """
        _response = self._raw_client.create_subscription(
            url=url, event_types=event_types, secret=secret, request_options=request_options
        )
        return _response.data

    def get_subscription(
        self,
        subscription_id: str,
        *,
        include_secret: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Retrieve a specific webhook subscription with its recent delivery attempts.

        Returns the subscription configuration along with a history of message delivery
        attempts. This is useful for debugging delivery issues or verifying that your
        endpoint is correctly receiving events.

        Use `include_secret=true` to also retrieve the signing secret for webhook
        signature verification. Keep this secret secure.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to retrieve (UUID).

        include_secret : typing.Optional[bool]
            Include the signing secret for webhook signature verification. Keep this secret secure and use it to verify the 'svix-signature' header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Subscription with delivery attempts

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_subscription(
            subscription_id="550e8400-e29b-41d4-a716-446655440000",
            include_secret=True,
        )
        """
        _response = self._raw_client.get_subscription(
            subscription_id, include_secret=include_secret, request_options=request_options
        )
        return _response.data

    def delete_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookSubscription:
        """
        Permanently delete a webhook subscription.

        Once deleted, Airweave will stop sending events to this endpoint immediately.
        This action cannot be undone. Any pending message deliveries will be cancelled.

        If you want to temporarily stop receiving events, consider disabling the
        subscription instead using the PATCH endpoint.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to delete (UUID).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Deleted subscription

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete_subscription(
            subscription_id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.delete_subscription(subscription_id, request_options=request_options)
        return _response.data

    def patch_subscription(
        self,
        subscription_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[EventType]] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        recover_since: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Update an existing webhook subscription.

        Use this endpoint to modify a subscription's configuration. You can:

        - **Change the URL**: Update where events are delivered
        - **Update event types**: Modify which events trigger notifications
        - **Enable/disable**: Temporarily pause delivery without deleting the subscription
        - **Recover messages**: When re-enabling, optionally recover missed messages

        Only include the fields you want to change. Omitted fields will retain their
        current values.

        When re-enabling a subscription (`disabled: false`), you can optionally provide
        `recover_since` to automatically retry all messages that were generated while
        the subscription was disabled.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to update (UUID).

        url : typing.Optional[str]
            New URL for webhook delivery. Must be a publicly accessible HTTPS endpoint.

        event_types : typing.Optional[typing.Sequence[EventType]]
            New list of event types to subscribe to. This replaces the existing list entirely.

        disabled : typing.Optional[bool]
            Set to `true` to pause delivery to this subscription, or `false` to resume. Disabled subscriptions will not receive events.

        recover_since : typing.Optional[dt.datetime]
            When re-enabling a subscription (`disabled: false`), optionally recover failed messages from this timestamp. Only applies when enabling.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Updated subscription

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.patch_subscription(
            subscription_id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._raw_client.patch_subscription(
            subscription_id,
            url=url,
            event_types=event_types,
            disabled=disabled,
            recover_since=recover_since,
            request_options=request_options,
        )
        return _response.data

    def recover_failed_messages(
        self,
        subscription_id: str,
        *,
        since: dt.datetime,
        until: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecoveryTask:
        """
        Retry failed message deliveries for a webhook subscription.

        Triggers a recovery process that replays all failed messages within the
        specified time window. This is useful when:

        - Your endpoint was temporarily down and you want to catch up
        - You've fixed a bug in your webhook handler
        - You want to reprocess events after re-enabling a disabled subscription

        Messages are retried in chronological order. Successfully delivered messages
        are skipped; only failed or pending messages are retried.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to recover messages for (UUID).

        since : dt.datetime
            Start of the recovery time window (inclusive). All failed messages from this time onward will be retried.

        until : typing.Optional[dt.datetime]
            End of the recovery time window (exclusive). If not specified, recovers all failed messages up to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecoveryTask
            Recovery task information

        Examples
        --------
        import datetime

        from airweave import AirweaveSDK

        client = AirweaveSDK(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.recover_failed_messages(
            subscription_id="550e8400-e29b-41d4-a716-446655440000",
            since=datetime.datetime.fromisoformat(
                "2024-03-14 00:00:00+00:00",
            ),
        )
        """
        _response = self._raw_client.recover_failed_messages(
            subscription_id, since=since, until=until, request_options=request_options
        )
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def get_messages(
        self,
        *,
        event_types: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[WebhookMessage]:
        """
        Retrieve all webhook messages for your organization.

        Webhook messages represent payloads that were sent (or attempted to be sent)
        to your subscribed endpoints. Each message contains the event type, payload data,
        and delivery status information.

        Use the `event_types` query parameter to filter messages by specific event types,
        such as `sync.completed` or `sync.failed`.

        Parameters
        ----------
        event_types : typing.Optional[typing.Union[str, typing.Sequence[str]]]
            Filter messages by event type(s). Accepts multiple values, e.g., `?event_types=sync.completed&event_types=sync.failed`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WebhookMessage]
            List of webhook messages

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_messages()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_messages(event_types=event_types, request_options=request_options)
        return _response.data

    async def get_message(
        self,
        message_id: str,
        *,
        include_attempts: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookMessageWithAttempts:
        """
        Retrieve a specific webhook message by its ID.

        Returns the full message details including the event type, payload data,
        timestamp, and delivery channel information. Use this to inspect the
        exact payload that was sent to your webhook endpoints.

        Use `include_attempts=true` to also retrieve delivery attempts for this message,
        which include HTTP response codes, response bodies, and timestamps for debugging
        delivery failures.

        Parameters
        ----------
        message_id : str
            The unique identifier of the message to retrieve (UUID).

        include_attempts : typing.Optional[bool]
            Include delivery attempts for this message. Each attempt includes the HTTP response code, response body, and timestamp.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookMessageWithAttempts
            Webhook message details

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_message(
                message_id="550e8400-e29b-41d4-a716-446655440000",
                include_attempts=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_message(
            message_id, include_attempts=include_attempts, request_options=request_options
        )
        return _response.data

    async def get_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[WebhookSubscription]:
        """
        List all webhook subscriptions for your organization.

        Returns all configured webhook endpoints, including their URLs, subscribed
        event types, and current status (enabled/disabled). Use this to audit
        your webhook configuration or find a specific subscription.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[WebhookSubscription]
            List of webhook subscriptions

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_subscriptions()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscriptions(request_options=request_options)
        return _response.data

    async def create_subscription(
        self,
        *,
        url: str,
        event_types: typing.Sequence[EventType],
        secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Create a new webhook subscription.

        Webhook subscriptions allow you to receive real-time notifications when events
        occur in Airweave. When you create a subscription, you specify:

        - **URL**: The HTTPS endpoint where events will be delivered
        - **Event Types**: Which events you want to receive (e.g., `sync.completed`, `sync.failed`)
        - **Secret** (optional): A custom signing secret for verifying webhook signatures

        After creation, Airweave will send HTTP POST requests to your URL whenever
        matching events occur. Each request includes a signature header for verification.

        Parameters
        ----------
        url : str
            The HTTPS URL where webhook events will be delivered. Must be a publicly accessible endpoint that returns a 2xx status code.

        event_types : typing.Sequence[EventType]
            List of event types to subscribe to. Events not in this list will not be delivered to this subscription. Available types: `sync.pending`, `sync.running`, `sync.completed`, `sync.failed`, `sync.cancelled`.

        secret : typing.Optional[str]
            Optional custom signing secret for webhook signature verification. If not provided, a secure secret will be auto-generated. Must be at least 24 characters if specified.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Created subscription

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.create_subscription(
                url="https://api.mycompany.com/webhooks/airweave",
                event_types=["sync.completed", "sync.failed"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_subscription(
            url=url, event_types=event_types, secret=secret, request_options=request_options
        )
        return _response.data

    async def get_subscription(
        self,
        subscription_id: str,
        *,
        include_secret: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Retrieve a specific webhook subscription with its recent delivery attempts.

        Returns the subscription configuration along with a history of message delivery
        attempts. This is useful for debugging delivery issues or verifying that your
        endpoint is correctly receiving events.

        Use `include_secret=true` to also retrieve the signing secret for webhook
        signature verification. Keep this secret secure.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to retrieve (UUID).

        include_secret : typing.Optional[bool]
            Include the signing secret for webhook signature verification. Keep this secret secure and use it to verify the 'svix-signature' header.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Subscription with delivery attempts

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_subscription(
                subscription_id="550e8400-e29b-41d4-a716-446655440000",
                include_secret=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscription(
            subscription_id, include_secret=include_secret, request_options=request_options
        )
        return _response.data

    async def delete_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookSubscription:
        """
        Permanently delete a webhook subscription.

        Once deleted, Airweave will stop sending events to this endpoint immediately.
        This action cannot be undone. Any pending message deliveries will be cancelled.

        If you want to temporarily stop receiving events, consider disabling the
        subscription instead using the PATCH endpoint.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to delete (UUID).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Deleted subscription

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete_subscription(
                subscription_id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_subscription(subscription_id, request_options=request_options)
        return _response.data

    async def patch_subscription(
        self,
        subscription_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[EventType]] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        recover_since: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhookSubscription:
        """
        Update an existing webhook subscription.

        Use this endpoint to modify a subscription's configuration. You can:

        - **Change the URL**: Update where events are delivered
        - **Update event types**: Modify which events trigger notifications
        - **Enable/disable**: Temporarily pause delivery without deleting the subscription
        - **Recover messages**: When re-enabling, optionally recover missed messages

        Only include the fields you want to change. Omitted fields will retain their
        current values.

        When re-enabling a subscription (`disabled: false`), you can optionally provide
        `recover_since` to automatically retry all messages that were generated while
        the subscription was disabled.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to update (UUID).

        url : typing.Optional[str]
            New URL for webhook delivery. Must be a publicly accessible HTTPS endpoint.

        event_types : typing.Optional[typing.Sequence[EventType]]
            New list of event types to subscribe to. This replaces the existing list entirely.

        disabled : typing.Optional[bool]
            Set to `true` to pause delivery to this subscription, or `false` to resume. Disabled subscriptions will not receive events.

        recover_since : typing.Optional[dt.datetime]
            When re-enabling a subscription (`disabled: false`), optionally recover failed messages from this timestamp. Only applies when enabling.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookSubscription
            Updated subscription

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.patch_subscription(
                subscription_id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch_subscription(
            subscription_id,
            url=url,
            event_types=event_types,
            disabled=disabled,
            recover_since=recover_since,
            request_options=request_options,
        )
        return _response.data

    async def recover_failed_messages(
        self,
        subscription_id: str,
        *,
        since: dt.datetime,
        until: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecoveryTask:
        """
        Retry failed message deliveries for a webhook subscription.

        Triggers a recovery process that replays all failed messages within the
        specified time window. This is useful when:

        - Your endpoint was temporarily down and you want to catch up
        - You've fixed a bug in your webhook handler
        - You want to reprocess events after re-enabling a disabled subscription

        Messages are retried in chronological order. Successfully delivered messages
        are skipped; only failed or pending messages are retried.

        Parameters
        ----------
        subscription_id : str
            The unique identifier of the subscription to recover messages for (UUID).

        since : dt.datetime
            Start of the recovery time window (inclusive). All failed messages from this time onward will be retried.

        until : typing.Optional[dt.datetime]
            End of the recovery time window (exclusive). If not specified, recovers all failed messages up to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecoveryTask
            Recovery task information

        Examples
        --------
        import asyncio
        import datetime

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.recover_failed_messages(
                subscription_id="550e8400-e29b-41d4-a716-446655440000",
                since=datetime.datetime.fromisoformat(
                    "2024-03-14 00:00:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.recover_failed_messages(
            subscription_id, since=since, until=until, request_options=request_options
        )
        return _response.data
