# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.enable_endpoint_request import EnableEndpointRequest
from ..types.endpoint_out import EndpointOut
from ..types.endpoint_secret_out import EndpointSecretOut
from ..types.event_type import EventType
from ..types.message_attempt_out import MessageAttemptOut
from ..types.message_out import MessageOut
from ..types.recover_out import RecoverOut
from ..types.subscription_with_attempts_out import SubscriptionWithAttemptsOut
from .raw_client import AsyncRawEventsClient, RawEventsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def get_messages(
        self,
        *,
        event_types: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[MessageOut]:
        """
        Get event messages for the current organization.

        Args:
            ctx: The API context containing organization info.
            event_types: Optional list of event types to filter by.

        Returns:
            List of event messages.

        Parameters
        ----------
        event_types : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageOut]
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_messages()
        """
        _response = self._raw_client.get_messages(event_types=event_types, request_options=request_options)
        return _response.data

    def get_message(self, message_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> MessageOut:
        """
        Get a specific event message by ID.

        Args:
            message_id: The ID of the message to retrieve.
            ctx: The API context containing organization info.

        Returns:
            The event message with its payload.

        Parameters
        ----------
        message_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_message(
            message_id="message_id",
        )
        """
        _response = self._raw_client.get_message(message_id, request_options=request_options)
        return _response.data

    def get_message_attempts(
        self, message_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[MessageAttemptOut]:
        """
        Get delivery attempts for a specific message.

        Args:
            message_id: The ID of the message.
            ctx: The API context containing organization info.

        Returns:
            List of delivery attempts for this message.

        Parameters
        ----------
        message_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageAttemptOut]
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_message_attempts(
            message_id="message_id",
        )
        """
        _response = self._raw_client.get_message_attempts(message_id, request_options=request_options)
        return _response.data

    def get_subscriptions(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[EndpointOut]:
        """
        Get all webhook subscriptions for the current organization.

        Args:
            ctx: The API context containing organization info.

        Returns:
            List of webhook subscriptions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EndpointOut]
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_subscriptions()
        """
        _response = self._raw_client.get_subscriptions(request_options=request_options)
        return _response.data

    def create_subscription(
        self,
        *,
        url: str,
        event_types: typing.Sequence[EventType],
        secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Create a new webhook subscription.

        Args:
            request: The subscription creation request.
            ctx: The API context containing organization info.

        Returns:
            The created subscription.

        Parameters
        ----------
        url : str

        event_types : typing.Sequence[EventType]

        secret : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.create_subscription(
            url="url",
            event_types=["sync.pending"],
        )
        """
        _response = self._raw_client.create_subscription(
            url=url, event_types=event_types, secret=secret, request_options=request_options
        )
        return _response.data

    def get_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionWithAttemptsOut:
        """
        Get a specific webhook subscription with its delivery attempts.

        Args:
            subscription_id: The ID of the subscription to retrieve.
            ctx: The API context containing organization info.

        Returns:
            The subscription details with message delivery attempts.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionWithAttemptsOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.get_subscription(subscription_id, request_options=request_options)
        return _response.data

    def delete_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete a webhook subscription.

        Args:
            subscription_id: The ID of the subscription to delete.
            ctx: The API context containing organization info.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.delete_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.delete_subscription(subscription_id, request_options=request_options)
        return _response.data

    def patch_subscription(
        self,
        subscription_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[EventType]] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Update a webhook subscription.

        Args:
            subscription_id: The ID of the subscription to update.
            request: The subscription update request.
            ctx: The API context containing organization info.

        Returns:
            The updated subscription.

        Parameters
        ----------
        subscription_id : str

        url : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[EventType]]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.patch_subscription(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.patch_subscription(
            subscription_id, url=url, event_types=event_types, disabled=disabled, request_options=request_options
        )
        return _response.data

    def enable_subscription(
        self,
        subscription_id: str,
        *,
        request: typing.Optional[EnableEndpointRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Enable a disabled webhook subscription, optionally recovering failed messages.

        Args:
            subscription_id: The ID of the subscription to enable.
            request: Optional request with recovery time range.
            ctx: The API context containing organization info.

        Returns:
            The enabled subscription.

        Parameters
        ----------
        subscription_id : str

        request : typing.Optional[EnableEndpointRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK, EnableEndpointRequest

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.enable_subscription(
            subscription_id="subscription_id",
            request=EnableEndpointRequest(),
        )
        """
        _response = self._raw_client.enable_subscription(
            subscription_id, request=request, request_options=request_options
        )
        return _response.data

    def get_subscription_secret(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EndpointSecretOut:
        """
        Get the signing secret for a webhook subscription.

        Args:
            subscription_id: The ID of the subscription.
            ctx: The API context containing organization info.

        Returns:
            The subscription's signing secret.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointSecretOut
            Successful Response

        Examples
        --------
        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.get_subscription_secret(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.get_subscription_secret(subscription_id, request_options=request_options)
        return _response.data

    def recover_failed_messages(
        self,
        subscription_id: str,
        *,
        since: dt.datetime,
        until: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecoverOut:
        """
        Recover (retry) failed messages for a webhook subscription.

        This endpoint triggers a recovery of all failed messages since the specified
        time. Useful after re-enabling a disabled endpoint to retry messages that
        failed while the endpoint was down.

        Args:
            subscription_id: The ID of the subscription to recover messages for.
            request: The recovery request with time range.
            ctx: The API context containing organization info.

        Returns:
            Information about the recovery task.

        Parameters
        ----------
        subscription_id : str

        since : dt.datetime

        until : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecoverOut
            Successful Response

        Examples
        --------
        import datetime

        from airweave import AirweaveSDK

        client = AirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )
        client.events.recover_failed_messages(
            subscription_id="subscription_id",
            since=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.recover_failed_messages(
            subscription_id, since=since, until=until, request_options=request_options
        )
        return _response.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def get_messages(
        self,
        *,
        event_types: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[MessageOut]:
        """
        Get event messages for the current organization.

        Args:
            ctx: The API context containing organization info.
            event_types: Optional list of event types to filter by.

        Returns:
            List of event messages.

        Parameters
        ----------
        event_types : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageOut]
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_messages()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_messages(event_types=event_types, request_options=request_options)
        return _response.data

    async def get_message(
        self, message_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> MessageOut:
        """
        Get a specific event message by ID.

        Args:
            message_id: The ID of the message to retrieve.
            ctx: The API context containing organization info.

        Returns:
            The event message with its payload.

        Parameters
        ----------
        message_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_message(
                message_id="message_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_message(message_id, request_options=request_options)
        return _response.data

    async def get_message_attempts(
        self, message_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[MessageAttemptOut]:
        """
        Get delivery attempts for a specific message.

        Args:
            message_id: The ID of the message.
            ctx: The API context containing organization info.

        Returns:
            List of delivery attempts for this message.

        Parameters
        ----------
        message_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[MessageAttemptOut]
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_message_attempts(
                message_id="message_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_message_attempts(message_id, request_options=request_options)
        return _response.data

    async def get_subscriptions(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[EndpointOut]:
        """
        Get all webhook subscriptions for the current organization.

        Args:
            ctx: The API context containing organization info.

        Returns:
            List of webhook subscriptions.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EndpointOut]
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_subscriptions()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscriptions(request_options=request_options)
        return _response.data

    async def create_subscription(
        self,
        *,
        url: str,
        event_types: typing.Sequence[EventType],
        secret: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Create a new webhook subscription.

        Args:
            request: The subscription creation request.
            ctx: The API context containing organization info.

        Returns:
            The created subscription.

        Parameters
        ----------
        url : str

        event_types : typing.Sequence[EventType]

        secret : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.create_subscription(
                url="url",
                event_types=["sync.pending"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_subscription(
            url=url, event_types=event_types, secret=secret, request_options=request_options
        )
        return _response.data

    async def get_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubscriptionWithAttemptsOut:
        """
        Get a specific webhook subscription with its delivery attempts.

        Args:
            subscription_id: The ID of the subscription to retrieve.
            ctx: The API context containing organization info.

        Returns:
            The subscription details with message delivery attempts.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubscriptionWithAttemptsOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_subscription(
                subscription_id="subscription_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscription(subscription_id, request_options=request_options)
        return _response.data

    async def delete_subscription(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete a webhook subscription.

        Args:
            subscription_id: The ID of the subscription to delete.
            ctx: The API context containing organization info.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.delete_subscription(
                subscription_id="subscription_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_subscription(subscription_id, request_options=request_options)
        return _response.data

    async def patch_subscription(
        self,
        subscription_id: str,
        *,
        url: typing.Optional[str] = OMIT,
        event_types: typing.Optional[typing.Sequence[EventType]] = OMIT,
        disabled: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Update a webhook subscription.

        Args:
            subscription_id: The ID of the subscription to update.
            request: The subscription update request.
            ctx: The API context containing organization info.

        Returns:
            The updated subscription.

        Parameters
        ----------
        subscription_id : str

        url : typing.Optional[str]

        event_types : typing.Optional[typing.Sequence[EventType]]

        disabled : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.patch_subscription(
                subscription_id="subscription_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch_subscription(
            subscription_id, url=url, event_types=event_types, disabled=disabled, request_options=request_options
        )
        return _response.data

    async def enable_subscription(
        self,
        subscription_id: str,
        *,
        request: typing.Optional[EnableEndpointRequest] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EndpointOut:
        """
        Enable a disabled webhook subscription, optionally recovering failed messages.

        Args:
            subscription_id: The ID of the subscription to enable.
            request: Optional request with recovery time range.
            ctx: The API context containing organization info.

        Returns:
            The enabled subscription.

        Parameters
        ----------
        subscription_id : str

        request : typing.Optional[EnableEndpointRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK, EnableEndpointRequest

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.enable_subscription(
                subscription_id="subscription_id",
                request=EnableEndpointRequest(),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.enable_subscription(
            subscription_id, request=request, request_options=request_options
        )
        return _response.data

    async def get_subscription_secret(
        self, subscription_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EndpointSecretOut:
        """
        Get the signing secret for a webhook subscription.

        Args:
            subscription_id: The ID of the subscription.
            ctx: The API context containing organization info.

        Returns:
            The subscription's signing secret.

        Parameters
        ----------
        subscription_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EndpointSecretOut
            Successful Response

        Examples
        --------
        import asyncio

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.get_subscription_secret(
                subscription_id="subscription_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subscription_secret(subscription_id, request_options=request_options)
        return _response.data

    async def recover_failed_messages(
        self,
        subscription_id: str,
        *,
        since: dt.datetime,
        until: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecoverOut:
        """
        Recover (retry) failed messages for a webhook subscription.

        This endpoint triggers a recovery of all failed messages since the specified
        time. Useful after re-enabling a disabled endpoint to retry messages that
        failed while the endpoint was down.

        Args:
            subscription_id: The ID of the subscription to recover messages for.
            request: The recovery request with time range.
            ctx: The API context containing organization info.

        Returns:
            Information about the recovery task.

        Parameters
        ----------
        subscription_id : str

        since : dt.datetime

        until : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecoverOut
            Successful Response

        Examples
        --------
        import asyncio
        import datetime

        from airweave import AsyncAirweaveSDK

        client = AsyncAirweaveSDK(
            framework_name="YOUR_FRAMEWORK_NAME",
            framework_version="YOUR_FRAMEWORK_VERSION",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.events.recover_failed_messages(
                subscription_id="subscription_id",
                since=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.recover_failed_messages(
            subscription_id, since=since, until=until, request_options=request_options
        )
        return _response.data
