# This file was auto-generated by Fern from our API Definition.

import contextlib
import json
import typing
from json.decoder import JSONDecodeError

import httpx_sse
from ...core.api_error import ApiError
from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.http_response import AsyncHttpResponse, HttpResponse
from ...core.jsonable_encoder import jsonable_encoder
from ...core.pydantic_utilities import parse_obj_as
from ...core.request_options import RequestOptions
from ...core.serialization import convert_and_respect_annotation_metadata
from ...errors.unprocessable_entity_error import UnprocessableEntityError
from ...types.agentic_search_event import AgenticSearchEvent
from ...types.filter_group import FilterGroup
from ...types.retrieval_strategy import RetrievalStrategy
from ...types.search_v_2_response import SearchV2Response

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def instant(
        self,
        readable_id: str,
        *,
        query: str,
        retrieval_strategy: typing.Optional[RetrievalStrategy] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchV2Response]:
        """
        Direct vector search.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        retrieval_strategy : typing.Optional[RetrievalStrategy]
            Which retrieval strategy to use.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results to return.

        offset : typing.Optional[int]
            Number of results to skip.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchV2Response]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/instant",
            method="POST",
            json={
                "query": query,
                "retrieval_strategy": retrieval_strategy,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
                "offset": offset,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def classic(
        self,
        readable_id: str,
        *,
        query: str,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchV2Response]:
        """
        AI-optimized search.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results to return.

        offset : typing.Optional[int]
            Number of results to skip.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchV2Response]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/classic",
            method="POST",
            json={
                "query": query,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
                "offset": offset,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def agentic(
        self,
        readable_id: str,
        *,
        query: str,
        thinking: typing.Optional[bool] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[SearchV2Response]:
        """
        Agent that iteratively searches, reads, navigates hierarchies, and collects results.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        thinking : typing.Optional[bool]
            Enable extended thinking / chain-of-thought.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results. None means agent decides.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchV2Response]
            Successful Response
        """
        _response = self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/agentic",
            method="POST",
            json={
                "query": query,
                "thinking": thinking,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.contextmanager
    def stream_agentic(
        self,
        readable_id: str,
        *,
        query: str,
        thinking: typing.Optional[bool] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[HttpResponse[typing.Iterator[AgenticSearchEvent]]]:
        """
        Streaming agentic search via Server-Sent Events. Returns real-time events as the agent searches.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        thinking : typing.Optional[bool]
            Enable extended thinking / chain-of-thought.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results. None means agent decides.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[HttpResponse[typing.Iterator[AgenticSearchEvent]]]
            SSE stream of agentic search events.
        """
        with self._client_wrapper.httpx_client.stream(
            f"collections/{jsonable_encoder(readable_id)}/search/agentic/stream",
            method="POST",
            json={
                "query": query,
                "thinking": thinking,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            def _stream() -> HttpResponse[typing.Iterator[AgenticSearchEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        def _iter():
                            _event_source = httpx_sse.EventSource(_response)
                            for _sse in _event_source.iter_sse():
                                if _sse.data == None:
                                    return
                                try:
                                    yield typing.cast(
                                        AgenticSearchEvent,
                                        parse_obj_as(
                                            type_=AgenticSearchEvent,  # type: ignore
                                            object_=json.loads(_sse.data),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return HttpResponse(response=_response, data=_iter())
                    _response.read()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield _stream()


class AsyncRawSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def instant(
        self,
        readable_id: str,
        *,
        query: str,
        retrieval_strategy: typing.Optional[RetrievalStrategy] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchV2Response]:
        """
        Direct vector search.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        retrieval_strategy : typing.Optional[RetrievalStrategy]
            Which retrieval strategy to use.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results to return.

        offset : typing.Optional[int]
            Number of results to skip.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchV2Response]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/instant",
            method="POST",
            json={
                "query": query,
                "retrieval_strategy": retrieval_strategy,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
                "offset": offset,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def classic(
        self,
        readable_id: str,
        *,
        query: str,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        offset: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchV2Response]:
        """
        AI-optimized search.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results to return.

        offset : typing.Optional[int]
            Number of results to skip.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchV2Response]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/classic",
            method="POST",
            json={
                "query": query,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
                "offset": offset,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def agentic(
        self,
        readable_id: str,
        *,
        query: str,
        thinking: typing.Optional[bool] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[SearchV2Response]:
        """
        Agent that iteratively searches, reads, navigates hierarchies, and collects results.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        thinking : typing.Optional[bool]
            Enable extended thinking / chain-of-thought.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results. None means agent decides.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchV2Response]
            Successful Response
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"collections/{jsonable_encoder(readable_id)}/search/agentic",
            method="POST",
            json={
                "query": query,
                "thinking": thinking,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchV2Response,
                    parse_obj_as(
                        type_=SearchV2Response,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Optional[typing.Any],
                        parse_obj_as(
                            type_=typing.Optional[typing.Any],  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    @contextlib.asynccontextmanager
    async def stream_agentic(
        self,
        readable_id: str,
        *,
        query: str,
        thinking: typing.Optional[bool] = OMIT,
        filter: typing.Optional[typing.Sequence[FilterGroup]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[AgenticSearchEvent]]]:
        """
        Streaming agentic search via Server-Sent Events. Returns real-time events as the agent searches.

        Parameters
        ----------
        readable_id : str

        query : str
            Search query text.

        thinking : typing.Optional[bool]
            Enable extended thinking / chain-of-thought.

        filter : typing.Optional[typing.Sequence[FilterGroup]]
            Filter groups (combined with OR).

        limit : typing.Optional[int]
            Max results. None means agent decides.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[AsyncHttpResponse[typing.AsyncIterator[AgenticSearchEvent]]]
            SSE stream of agentic search events.
        """
        async with self._client_wrapper.httpx_client.stream(
            f"collections/{jsonable_encoder(readable_id)}/search/agentic/stream",
            method="POST",
            json={
                "query": query,
                "thinking": thinking,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=typing.Sequence[FilterGroup], direction="write"
                ),
                "limit": limit,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        ) as _response:

            async def _stream() -> AsyncHttpResponse[typing.AsyncIterator[AgenticSearchEvent]]:
                try:
                    if 200 <= _response.status_code < 300:

                        async def _iter():
                            _event_source = httpx_sse.EventSource(_response)
                            async for _sse in _event_source.aiter_sse():
                                if _sse.data == None:
                                    return
                                try:
                                    yield typing.cast(
                                        AgenticSearchEvent,
                                        parse_obj_as(
                                            type_=AgenticSearchEvent,  # type: ignore
                                            object_=json.loads(_sse.data),
                                        ),
                                    )
                                except Exception:
                                    pass
                            return

                        return AsyncHttpResponse(response=_response, data=_iter())
                    await _response.aread()
                    if _response.status_code == 422:
                        raise UnprocessableEntityError(
                            headers=dict(_response.headers),
                            body=typing.cast(
                                typing.Optional[typing.Any],
                                parse_obj_as(
                                    type_=typing.Optional[typing.Any],  # type: ignore
                                    object_=_response.json(),
                                ),
                            ),
                        )
                    _response_json = _response.json()
                except JSONDecodeError:
                    raise ApiError(
                        status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
                    )
                raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

            yield await _stream()
